instructions:
	echo "\n\nThere are three text files available:\nquote.txt\nLoremIpsum.txt\nulisses.txt\n\nTo compile the file run 'make compile'\n\nTo run the file run './samples *file.txt* *number of samples* *length of samples*'\n\nExample: samples quote.txt 5 7\n"

compile:
	gcc -Wall -o samples samples.c