instructions:
	echo "\n\nTo compile the file run 'make compile'\n\nTo clean pipe files run 'make clean'\n\nTo run the file run './tokenring *number of pipes* *probability* *time*'\n\nExample: tokenring 5 0.01 10\n"

clean:
	rm pipe*

compile:
	gcc -Wall -o tokenring tokenring.c